name: n8n-exp-1

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "127.0.0.1:8888:5678"
    environment:
      # Disable all cloud features and setup flows
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_HIRING_BANNER_ENABLED=false

      # Configure storage
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem

      # Disable public API
      # - N8N_PUBLIC_API_DISABLED=true
      # - N8N_PUBLIC_API_SWAGGERUI_DISABLED=true

      # SSL Settings
      # - N8N_SSL_CERT=/etc/ssl/certs/ssl.pem
      # - N8N_SSL_KEY=/etc/ssl/private/ssl.key

      # Security settings
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    ports:
      - "127.0.0.1:11434:11434"
    environment:
      - LLM_MODEL_TAG=qwen3:1.7b
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  mcp-newsdataapi:
    build:
      context: ./mcp-newsdataapi
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./mcp-newsdataapi/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  n8n_data:
  ollama_data:
